"""Migrations for product and images app."""

# Generated by Django 2.2.6 on 2019-10-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations for product and images app."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('product_type', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('stock', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(max_length=500, upload_to='images/')),
                ('image2', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
