# Generated by Django 5.0.7 on 2024-08-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
